#course_project pipeline base configuration

image: maven:latest

stages:
    - test

api-integration-tests:
    tags:
        - docker
    stage: test
    script:
        - cd course_project
        - mvn test -Papi-integration-tests
        - echo "api integration tests completed"

app-functionality-tests:
    tags:
        - docker
    stage: test
    script:
        - cd course_project
        - mvn test -Papp-functionality-tests
        - echo "app functionality tests completed"

    artifacts:
        when: always
        reports:
            junit:
                - course_project/target/surefire-reports/TEST-*.xml