#course_project pipeline base configuration

image: maven:latest

stages:
    - apitest

api-integration-tests:
    tags:
        - docker
    stage: apitest
    script:
        - cd course_project
        - mvn test -Papi-integration-tests
        - echo "api integration tests completed"

    artifacts:
        when: always
        reports:
            junit:
                - course_project/target/surefire-reports/TEST-*.xml